### ISSUE TITLE
Chevron logo placement

### ISSUE THREAD

**Issue by scrosseye** [learlab/itell#31]
Can we have the capacity to center images?

Also, there is a lot of white space between the logo and the title/requirements. What can we do about that?

**Comment by theannachen** [comment]
Unfortunately since this is a markdown restriction, we would need to create a new front end component for images. I believe there is one similar, but I am not sure how to utilize it yet. I will reach out to Qiushi and see how that will work.  For now, I believe downsizing the actual picture itself or using an html embed for it (using an <img> and an online url) would both work for at least resizing.
